import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDb Clone",
  description: "IMDb clone generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
